---
- hosts: all
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_agent2_hostname: Remote Secured
      zabbix_agent2_tlsaccept: psk
      zabbix_agent2_tlspsk_auto: true
      zabbix_agent_ip: 192.168.50.3 # You shouldn't typically need to set this explicitly
  vars_files:
    - remote-vars.yml
